name = "sandbox"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "public"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "sandbox-miami-storage"
preview_bucket_name = "sandbox-miami-storage-preview"
